### ISSUE TITLE
cluster client interface to call cluster service api

### ISSUE THREAD

**Issue by nurali-techie** [fabric8-services/fabric8-common#87]
env_serivce wants to call cluster_service API ([check_comment](https://github.com/fabric8-services/fabric8-env/issues/20#issuecomment-451380564)). With this issue, we will introduce similar cluster_client interface similar to auth_client in f8-common [auth_client_interface](https://github.com/fabric8-services/fabric8-common/blob/master/auth/service.go)

**Comment by alexeykazakov** [comment]
Basically you are talking about improved version of cluster-client here. We introduced auth client in common because auth is really a core functionality. But cluster service is more case specific. I'm afraid we will end up with adding too much to common lib.
What if we add a cluster service to https://github.com/fabric8-services/fabric8-cluster-client instead?
I guess we could make our client libs more smart instead of keeping the low level and auto-generated http clients there. It could contains of two parts:
1. The current http client stuff which is generated.
2. A service on top of the generated client with dependencies to common.

@nurali-techie @xcoulon @dipak-pawar WDYT? It would allow us to reuse this service in different repos instead of re-implementing it over and over again but it would make the client lib more "heavy" with additional dependencies like common.

**Comment by nurali-techie** [comment]
@alexeykazakov I am fine with both options to add improved_cluster_client.
Option1: Add into f8-common
Option2: Add into f8-cluster-client.

.. but I don't think currently we need to bother about f8-common getting bigger wrt codebase_size.  In case we think about binary_size then only few used packages from f8-common will be bundles with target service (i.e. env_service) and not f8-common deliver as a whole itself.

.. rather I think that we should develop a notion among development teams that whatever could be common among different services will be there in f8-common (common the name truely reflect common stuff).  So there is only one place (repo) for any developer to look after in case searching / adding particular common functionality.

So overall, I would prefer adding into f8-common over f8-cluster-client.

**Comment by dipak-pawar** [comment]
@nurali-techie, @alexeykazakov, After thinking about making it a generic wrapper for all clients,  it wouldn't add more than creation of client with required token, We can't add any api call specific implementation as common to all as every api will have different payload and responses. 

So, as discussed in our call, let's go ahead with option 2.

**Comment by alexeykazakov** [comment]
Yeah, agree. Payloads and returns are implementation specific and we can’t make them generic.
